### PR TITLE
installation requirements 

### PR DESCRIPTION
**Pull request by Tasm-Devil**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by zewelor** [comment]
bluepy should be auto installed on first run, when there is enabled worker, that uses it. All libs used by specifid workers, should be auto installed on run, which worker doesn't work ?

**Comment by Tasm-Devil** [comment]
Sorry i can't tell you. On my Linux MInt machine, it didn't wanted to run without this python package and there was no autoinstallation. I would include it in the requirements.

**Comment by zewelor** [comment]
Which worker ?

**Comment by Tasm-Devil** [comment]
blescanmulti.py

**Pull request closed without merging**
