### PR TITLE
add passive read for lywsd03mmc with custom firmware

### PR DESCRIPTION
**Pull request by westenberg**
# Description

The Xiaomi LYWSD03MMC can be flashed over Bluetooth, for more information: https://github.com/atc1441/ATC_MiThermometer

With the custom firmware the temperature, humidity and battery can be read passive. This change adds support for passive readout.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by zewelor** [comment]
Thanks for PR. I think it would be good to add some readme info that its for this custom FW. As I understand this sensors support passive reading, but encprypted, which won't work with this code. Maybe also add info in config.example, that this option works only in this custom firmware ?

**Comment by westenberg** [comment]
It’s not encrypted. Just flash the hygrometer over bluetooth, select custom type broadcast and the data is sent unencrypted in the advertisement. This change reads it directly.

**Comment by zewelor** [comment]
But its unencrypted, only after flashing this custom FW ? Official firmware needs encryption key: https://esphome.io/components/sensor/xiaomi_ble.html#lywsd03mmc . So with passive mode, it requires that custom fw. This should be noted somewhere

**Comment by westenberg** [comment]
Yes that’s true. You should upload the custom firmware over Bluetooth first in order to use passive readout and also set the custom advertisement setting from the Telink flasher (same page that you use for flashing the firmware) the info should be in de wiki. The steps for flashing are on https://github.com/atc1441/ATC_MiThermometer

I will add the info to te wiki this evening.

**Comment by zewelor** [comment]
I think it should be also good to add comment here: https://github.com/zewelor/bt-mqtt-gateway/pull/201/files#diff-8820e266c757e766e9a345e6aa55bcd237f1795744ed124b49c5c50434dcdbecR142 . At least with link to wiki etc

**Comment by westenberg** [comment]
added the comment in the config example. How should I edit the wiki (if still neccessary).

**Comment by zewelor** [comment]
Looks good ! Merged it and added short wiki info with link in config.sample. Thanks !

**Pull request merged**
