### PR TITLE
Replace deprecated hold and away modes with presets

### PR DESCRIPTION
**Pull request by cybe**
# Description

This addresses #261 were the separate hold and away topics got deprecated and merged into a preset topic. The technical behavior should be the same as before. Asking for a review from @merll, @krasnoukhov or @zewelor.

Pointers:
- `HOLD` mode is basically now a `PRESET` mode
- `AWAY` is moved to the preset category
- Renamed `STATE` to `MODE` and `HOLD` to `PRESET` to match the HA terminology

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by zewelor** [comment]
Looks good thanks !

**Comment by renarena** [comment]
I made the changes and restarted the docker and HA, but still no preset modes:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:140
Integration: Home Assistant WebSocket API (documentation, issues)
[139728229773184] Error handling message: Entity climate.thermostat_kitchen_climate does not support this service. (unknown_error)
```
Something else i have to do?

**Comment by cybe** [comment]
The MQTT snippet suggests that the fix is not in effect. There shouldn't be any `away_mode*` or `hold*` topics anymore. They got replaced with `preset_mode*` topics.

**Comment by renarena** [comment]
I edited the file in the docker container, executed docker-compose down and up, deleted the oldMQTT topic using MQTT Explorer. What else?

**Comment by cybe** [comment]
Do not edit the files inside the container. Just pull the new image, as it is already released:
```
docker-compose pull
docker-compose down
docker-compose up
```

**Comment by renarena** [comment]
sorry, the `Hi, could you please try out https://github.com/zewelor/bt-mqtt-gateway/pull/266 ?` looked not like there is an update i could pull, so i tried to patch the file.
Now its working.
Thank you!

**Comment by cybe** [comment]
You're welcome :)

**Pull request merged**
