### PR TITLE
Retry on failed BTLE operations

### PR DESCRIPTION
**Pull request by cybe**
Hey :)

# Description

This adds a generic retry mechanism when communicating with BTLE devices, based on [tenacity](https://tenacity.readthedocs.io/en/latest/). Before this addition I occasionally ran into BTLE disconnect errors:
```
12:07:46 Error during update of thermostat device 'bedroom' (00:1A:22:10:9A:43): BTLEDisconnectError
```
Now every communication attempt is tried at max three times with an exponential backoff, like this (debug output):
```
04:10:39 Call to workers.thermostat.update_device_state failed the 1 time (BTLEDisconnectError). Retrying in 4.0 seconds
```
I'm quite happy with the result, I'm almost down to zero failed connections. If also the third attempt fails, the original exception is raised.

For developers, this can be used either as a decorator (with an optional exception_type):
```
from workers.base import retry

@retry(exception_type=BTLEDisconnectError)
def update():
  communicate()

update()
```
Or inline:
```
from workers.base import retry

def update():
  communicate()

retry(update, exception_type=BTLEDisconnectError)()
```

For now, this is only included for the devices I actually use: miflora, mithermometer, thermostat.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by zewelor** [comment]
Looks good. I'm only thinking about hardcoded options, and retry by default. If I understand correctly with 4 thermostats, when one sometimes fails, whole worker update can easily take more than 30s timeout ( in workers manager ). Instead of quick connection error and retry in another round. Maybe it should be configurable, per worker, with ability to turn off retry ( by retry_count 0 ? ).

**Comment by cybe** [comment]
Valid points. This is why I bumped the timeout values via #62 ;)

I make the retry count configurable. I'm not yet sure what the default should be though. I'm actually leaning towards no retry.

**Comment by zewelor** [comment]
I think 0 retry is good default. Also now I think that there should be separate retry for status update and commands. In case of usually failing device. Probably you don't want any retry or one, but for command more retries as you know it fails more frequent than other devices.

**Comment by ronytomen** [comment]
Other implementations I have seen that communicate with Xiaomi BLE sensors have been around 2 to 3 retries as the default.

**Comment by dbluxo** [comment]
I sometimes have `BluetoothBackendExceptions` and would be very happy if there was a retry mechanism :blush:

**Comment by cybe** [comment]
Retries are now configurable for updates and commands (globally and optionally per worker). `0` retries is the default.

This is still only applied to the devices I actually use: miflora, mithermometer, thermostat. Other workers would just ignore those retry-settings.

**Comment by cybe** [comment]
Note: From a users perspective I would prefer a more generic solution that automatically covers all workers. But I'm unsure how to approach this, as every worker handles its communication differently.

Anyway, I would like someone to actually tests this before merging (I could provide a docker image). I could also add retries to other workers if that person uses those and is therefore able to test the retry implementation.

@zewelor Would it be possible to automatically generate and push Dockerimages for PRs?

**Comment by dbluxo** [comment]
> Anyway, I would like someone to actually tests this before merging (I could provide a docker image). I could also add retries to other workers if that person uses those and is therefore able to test the retry implementation.

Hi @cybe, I can offer to test the retry mechanism for miflora, would need the docker image for that.

**Comment by cybe** [comment]
> Hi @cybe, I can offer to test the retry mechanism for miflora, would need the docker image for that.

For which architecture? amd64? arm64? armv7?

**Comment by dbluxo** [comment]
> > Hi @cybe, I can offer to test the retry mechanism for miflora, would need the docker image for that.
> 
> For which architecture? amd64? arm64? armv7?

Thanks, I have now been able to build it locally, running your PR now for a while ☕

**Comment by dbluxo** [comment]
In the last 24 hours I had 77x `BluetoothBackendException`s, these were all successfully retried by the retry mechanism and the sensors returned values 🎉 👍 

I additionally also had 23x `exceptions.DeviceTimeoutError`, could these also be included in the retry mechanism or does that make no sense?

```
2021-01-27 18:15:03,393 INFO bt-mqtt-gw.workers.miflora miflora.py:106:status_update - Updating 2 miflora devices
2021-01-27 18:15:03,394 DEBUG bt-mqtt-gw.workers.miflora miflora.py:109:status_update - Updating miflora device 'planta' (00:00:00:00:00:0A)
2021-01-27 18:15:17,706 INFO bt-mqtt-gw.workers.base base.py:97:log_retry - Call to workers.miflora.update_device_state failed the 1 time (BluetoothBackendException). Retrying in 1.86 seconds
2021-01-27 18:15:27,398 ERROR bt-mqtt-gw.workers.miflora logger.py:50:log_exception - Time out during update of miflora device 'planta' (00:00:00:00:00:0A)
Traceback (most recent call last):
  File "/application/workers/miflora.py", line 114, in status_update
    yield retry(self.update_device_state, retries=self.update_retries, exception_type=BluetoothBackendException)(name, data["poller"])
  File "/application/workers/base.py", line 113, in wrapped_retry
    return retryer(func, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 423, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 360, in iter
    return fut.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/tenacity/__init__.py", line 426, in __call__
    result = fn(*args, **kwargs)
  File "/application/workers/miflora.py", line 142, in update_device_state
    payload=poller.parameter_value(attr),
  File "/usr/local/lib/python3.8/site-packages/miflora/miflora_poller.py", line 156, in parameter_value
    self.fill_cache()
  File "/usr/local/lib/python3.8/site-packages/miflora/miflora_poller.py", line 92, in fill_cache
    with self._bt_interface.connect(self._mac) as connection:
  File "/usr/local/lib/python3.8/site-packages/btlewrap/base.py", line 47, in __enter__
    self._backend.connect(self._mac)
  File "/usr/local/lib/python3.8/site-packages/btlewrap/bluepy.py", line 27, in _func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/btlewrap/bluepy.py", line 56, in connect
    self._peripheral = Peripheral(mac, iface=iface, addrType=self.address_type)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 436, in _connect
    rsp = self._getResp('stat')
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.8/site-packages/bluepy/btle.py", line 347, in _waitResp
    rv = self._helper.stdout.readline()
  File "/usr/local/lib/python3.8/site-packages/interruptingcow/__init__.py", line 74, in handler
    raise exception
exceptions.DeviceTimeoutError
2021-01-27 18:15:27,405 DEBUG bt-mqtt-gw.workers.miflora miflora.py:109:status_update - Updating miflora device 'plantb' (00:00:00:00:00:0B)
2021-01-27 18:15:29,685 INFO bt-mqtt-gw.workers.base base.py:97:log_retry - Call to workers.miflora.update_device_state failed the 1 time (BluetoothBackendException). Retrying in 2.44 seconds
2021-01-27 18:15:35,891 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:57:execute - Execution result of command MifloraWorker.status_update: [{'topic': 'miflora/plantb/temperature', 'payload': '21.7'}, {'topic': 'miflora/plantb/moisture', 'payload': '56'}, {'topic': 'miflora/plantb/light', 'payload': '0'}, {'topic': 'miflora/plantb/conductivity', 'payload': '670'}, {'topic': 'miflora/plantb/battery', 'payload': '100'}, {'topic': 'miflora/plantb/low_battery', 'payload': 'OFF'}]
```

**Comment by cybe** [comment]
Great to hear!

> I had additionally also 23x `exceptions.DeviceTimeoutError`s, where then no values were delivered, could these also be included in the retry mechanism, or does this not make sense?

Yeah, the whole interplay between retries and timeouts is currently quite finicky. I try my best to explain:

The timeout you are most likely being affected by is controlled by the [per_device_timeout](https://github.com/zewelor/bt-mqtt-gateway/blob/634eefd4c5acca28c0f89a8c9d1227b40ea77a44/config.yaml.example#L69) value. The retry mechanism still respects that. So even if you configure 100 retries, those must still be within that `per_device_timeout` timeout. Try to increase it.

But be also aware that this per device timeout must still be within the global timeout value [command_timeout](https://github.com/zewelor/bt-mqtt-gateway/blob/634eefd4c5acca28c0f89a8c9d1227b40ea77a44/config.yaml.example#L20) (which could also be overridden from within a [worker](https://github.com/zewelor/bt-mqtt-gateway/blob/634eefd4c5acca28c0f89a8c9d1227b40ea77a44/config.yaml.example#L23))

You should also consider the [update_interval](https://github.com/zewelor/bt-mqtt-gateway/blob/634eefd4c5acca28c0f89a8c9d1227b40ea77a44/config.yaml.example#L70), so that your global timeout is less than `update_interval`. Otherwise you might get interleaving update operations.

**Comment by dbluxo** [comment]
@cybe Thanks for the excellent explanation! 💯 I was able to adjust my values so now no additional exceptions have occurred in the last 24 hours 🎉

**Comment by zewelor** [comment]
@cybe Added support for building pr docker images. Can you rebase on newest master to try it ?

**Comment by zewelor** [comment]
@cybe try now again plz.

**Comment by zewelor** [comment]
Not sure how to make it work. Now also started to read: https://securitylab.github.com/research/github-actions-preventing-pwn-requests . Pushing to docker hub needs access to repo secrets, thats when it starts complicated from what I can read :\

**Comment by cybe** [comment]
> Not sure how to make it work. Now also started to read: https://securitylab.github.com/research/github-actions-preventing-pwn-requests . Pushing to docker hub needs access to repo secrets, thats when it starts complicated from what I can read :\

I'll take a look at that tomorrow. If PR-builds introduce security issues, better leave it disabled.

**Comment by cybe** [comment]
> I'll take a look at that tomorrow. If PR-builds introduce security issues, better leave it disabled.

This looks rather complicated and should be implemented very carefully (if at all). But lets keep this PR clean if this.

**Comment by cybe** [comment]
Back on topic: I consider this PR ready. I'm still a bit on the fence with the naming scheme though. We differentiate between commands (sending out actions) and updates (requests status updates). However: the configuration `command_timeout` relates to both. But I guess we should tackle that issue elsewhere. In fact: I'd like to restructure the timeout behavior, possibly integrating it into "tenacity".

**Comment by zewelor** [comment]
I think it would be good to merge it asap, and do some tweaks later. Thanks for great work !

As for building docker, maybe lets make some development branch, and merge some longer PR's there, and it will be auto build .

**Pull request merged**
