### PR TITLE
Test force utc timezone

### PR DESCRIPTION
**Pull request by zewelor**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by kenand1970** [comment]
Thanks, 
It works on Synology (DSM 6.1.x)

**Comment by kenand1970** [comment]
Dear Zewelor,

I saw new addition in Wiki
https://github.com/zewelor/bt-mqtt-gateway/wiki/Upgrade-Bluez

I'm not sure, but It' s my opinion  Install json-c and  4 Install ell also
need for Bluez 5.50

I use them when I compile Bluez 5.50 ( in  pi zero w)

  2.3 Install json-c for BlueZ v5.50 :
cd ~
wget https://s3.amazonaws.com/json-c_releases/releases/json-c-0.13.tar.gz
tar -xvf json-c-0.13.tar.gz cd json-c-0.13/
sudo ./configure --prefix=/usr --disable-static && make
sudo make install

and

  2.4 Install ell for BlueZ v5.50
  cd ~
wget https://mirrors.edge.kernel.org/pub/linux/libs/ell/ell-0.6.tar.xz
tar -xvf ell-0.6.tar.xz cd ell-0.6/
sudo ./configure --prefix=/usr
sudo make
sudo make install

It's fact I'm not Linux programmer . (I'm physician)

Regards

Andras











zewelor <notifications@github.com> ezt írta (időpont: 2019. febr. 12., K,
7:01):

**Comment by zewelor** [comment]
On what os ? I've tested it on rpi and work, maybe they are preinstalled ?

**Comment by kenand1970** [comment]
Dear Zewelor,

I used this guideline (it wrote  for PI):
https://www.bluetooth.com/~/media/files/developer/t1804_how%20to%20set%20up%20bluez_lfc_final.ashx?la=en

I used raspbian on my Pi zero W and *json-c* and  l *ell *was missing. I
got error wihout json-c. I compiled them from surce like guidline before
compiled Bluez 5.50

May you write to WIKI if   json-c or ell are missing user  follows this
guide (Step-by-Step Guide
How to Deploy BlueZ on Raspberry Pi3 and Use It)

Best Regards

Andras

zewelor <notifications@github.com> ezt írta (időpont: 2019. febr. 12., K,
7:01):

**Comment by kenand1970** [comment]
Dear Zewelor,

I'm so sorry, but I have got new poblem with Synology and BT-MQTT

Modded script works and  ./gateway.py -d works well for  if I call It from
BT-MQTT directory.
mqtt-gateway.service do not work with synology, Synology has not got
systemctl

If I simple call  gateway.py from external directory I recive error

/volume1/homes/admin/bt-mqtt-gateway/gateway.py


root@BirxNAS:/volume1/homes/admin#
/volume1/homes/admin/bt-mqtt-gateway/gateway.py
Traceback (most recent call last):
  File "/volume1/homes/admin/bt-mqtt-gateway/gateway.py", line 13, in
<module>
    from config import settings
  File "/volume1/homes/admin/bt-mqtt-gateway/config.py", line 3, in <module>
    with open("config.yaml", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
root@BirxNAS:/volume1/homes/admin#

I if would like to autostart on Synology I have to put a conf file to
/etc/init
for exapmle bt-mqtt.conf

conf contains:
exec /volume1/homes/admin/bt-mqtt-gateway/gateway.py

But also receive same error :
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'

Have you got idea how can I solve this problem?

Regards

Andras


András Kenéz <kenez.andras@gmail.com> ezt írta (időpont: 2019. febr. 12.,
K, 14:45):

**Comment by bbbenji** [comment]
Do not put gateway.py in the autorun directory. Place a script which runs gateway.py in the autorun directory instead. The script must point to gateway.py which would be located somewhere else, like the home folder and contain config.yaml  and the other files.

**Comment by kenand1970** [comment]
Dear Benji,

Thank you very much your help.

I did not put gateway.py into autorun directory, I left it in-original
place: /volume1/homes/admin/bt-mqtt-gateway directory.
But if I give command  /volume1/homes/admin/bt-mqtt-gateway/gateway.py from
autorun directory ( /etc/init) receive error:

Traceback (most recent call last):
  File "/volume1/homes/admin/bt-mqtt-gateway/gateway.py", line 13, in
<module>
    from config import settings
  File "/volume1/homes/admin/bt-mqtt-gateway/config.py", line 3, in <module>
    with open("config.yaml", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
root@BirxNAS:/volume1/homes/admin#

Commands works only from   /volume1/homes/admin/bt-mqtt-gateway directory.

Regards

Andras



Benji <notifications@github.com> ezt írta (időpont: 2019. febr. 13., Sze,
20:31):

**Comment by bbbenji** [comment]
Try changing:

 https://github.com/zewelor/bt-mqtt-gateway/blob/master/config.py#L3

to:

```with open("/volume1/homes/admin/bt-mqtt-gateway/config.yaml", "r") as f:```

**Comment by kenand1970** [comment]
Thank very  much,

My  BT sensors busy from lof query at now I will test it tomorrow

Reagrds

Andras

Benji <notifications@github.com> ezt írta (időpont: 2019. febr. 13., Sze,
21:59):

**Comment by zewelor** [comment]
@kenand1970 Ive improved config location loading, you can try newest code, it should work without any modifications now.

**Comment by kenand1970** [comment]
Dear Zewelor,

I will try , thank you very much.

András

zewelor <notifications@github.com> ezt írta (időpont: 2019. febr. 14., Cs,
7:30):

**Comment by kenand1970** [comment]
Dear Zewelor,

Moddec code works, tahnks

Andras

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mentes
a vírusoktól. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

András Kenéz <kenez.andras@gmail.com> ezt írta (időpont: 2019. febr. 14.,
Cs, 8:34):

**Comment by kenand1970** [comment]
Dear Zewelor,

I tried your solution for Bluez 5.50 and works well.
https://github.com/zewelor/bt-mqtt-gateway/wiki/Upgrade-Bluez-on-Raspbian

I had to make some modification in  Synology, because optware has not got
every packages
After I disabled uvev and systemd I was able to compile

./configure --prefix=/usr --mandir=/usr/share/man --sysconfdir=/etc
--localstatedir=/var --enable-experimental --disable-udev
--disable-systemd

Thank you

Andras




zewelor <notifications@github.com> ezt írta (időpont: 2019. febr. 12., K,
14:30):

**Comment by zewelor** [comment]
Great to hear that. I've added your comment to wiki ( https://github.com/zewelor/bt-mqtt-gateway/wiki/Upgrade-Bluez-on-Raspbian ). Thanks

**Pull request merged**
