### PR TITLE
Thermostat state and mode mapping

### PR DESCRIPTION
**Pull request by krasnoukhov**
# Description

Since HA 0.96 the thermostat integration is really broken since HA introduced strict state/mode mapping. Here's a [commit](https://github.com/zewelor/bt-mqtt-gateway/commit/d1f2a1209262d08597da71c0426024369057ab14) to remove non-supported modes. This PR brings modes back by using "hold modes" which act like presets in the UI.

After this patch has been merged in HA these changes should work as expected: https://github.com/home-assistant/home-assistant/pull/28988

- New states: **Heat**, **Auto**, **Off** (breaking!)
- New presets for Heat: **Boost**, **Comfort** (manual), **Eco**, and the default **None** which sets state to **Off**
- Away mode is removed in favor of **Eco** preset (breaking!)
- **On** mode is not supported since there's no HA mapping (suggestions welcome, maybe map to [home](https://github.com/home-assistant/home-assistant/blob/ebc0ed1e22b4be80f2e11972987a63bfbae0bea8/homeassistant/components/climate/const.py#L51) or something?)

<details>
  <summary>Screenshot!</summary>

Home Assistant 2019-11-27 23-42-32
</details>

## Technical

- State and preset change are routed through a single handler since it's a single state in eq3bt anyway
- Mapping implementation has been separated into set/get handling since get has to set both state and mode

## Type of change

- [x] Bug fix
- [x] Breaking change

### CODE REVIEW

**Comment by zewelor** [comment]
Great thanks. I planned on working on this, but didn't had time yet ! So we should wait for new HA version ? Or even 2 more ( not sure if this PR gets into 103, as it might be too late for HA new features merge window ? )

**Comment by krasnoukhov** [comment]
I guess it's up to you, I'm not really sure about HA release schedule but hoping my change will make into a next release. I'm running HA from `dev` docker tag and it works great together!

Bonus screenshot when used with [simple-thermostat](https://github.com/nervetattoo/simple-thermostat):

Home Assistant 2019-11-28 00-14-55

**Comment by cybe** [comment]
Awesome! This was bothering me as well, but didn't had the time to actually fix it myself.

**Comment by zewelor** [comment]
HA 0.103 released with patch merged.

**Pull request merged**
